version: "3.1"
services:

  gin-demo:
    image: golang:alpine
    container_name: gin-demo
    restart: unless-stopped
    expose:
      - 8888
    ports:
      - 8888:8100
    env_file:
      - .env
    command: /bin/sh -c "cd /app && go install && go run main.go -p 8100"
    environment:
      TZ: Asia/Shanghai
      GIN_MODE: release
    volumes:
      - .:/app
      - venv:/root/.cache
volumes:
  venv:

